FORMAT: 1A
HOST: http://allthegreatshows.com/

# allthegreatshows

This API will be to display information about podcasts such as
different genres, hosts, and episides.

## Podcasts [/api/podcast]

### List All Podcasts [GET /api/podcast]

+ Response 200 (application/json)

        {
            "num_results": 1, 
            "objects": [
                {
                    "description": "", 
                    "episodes": [
                        {
                            "description": "", 
                            "file_url": "http://feedproxy.google.com/~r/TEDTalks_audio/~5/PA7gdCeKGaQ/MikeKinney_2017S.mp3", 
                            "id": 1, 
                            "podcast_id": 1, 
                            "published": "2017-10-23T15:13:02", 
                            "title": "A pro wrestler's guide to confidence | Mike Kinney"
                        }
                    ], 
                    "feed_url": "http://feeds.feedburner.com/TEDTalks_audio", 
                    "genres": [
                        {
                            "id": 1, 
                            "itunes_id": 1304, 
                            "name": "Education"
                        }, 

                    ], 
                    "id": 1, 
                    "image_url": "http://is4.mzstatic.com/image/thumb/Music128/v4/d5/c6/50/d5c65035-505e-b006-48e5-be3f0f8f19f8/source/600x600bb.jpg", 
                    "itunes_id": 160904630, 
                    "podcast_genre": [
                         {
                            "id": 1, 
                            "itunes_id": 1304, 
                            "name": "Education"
                        }, 
                    ], 
                    "provider": {
                        "id": 1, 
                        "itunes_id": null, 
                        "name": "TED"
                    }, 
                    "provider_id": 1, 
                    "title": "TED Talks Daily"
                },
            ],
            "page": 1, 
            "total_pages": 1
        }
        
### Get Podcast [GET /api/podcast/{ID}]

+ Response 200 (application/json)

         {
                    "description": "", 
                    "episodes": [
                        {
                            "description": "", 
                            "file_url": "http://feedproxy.google.com/~r/TEDTalks_audio/~5/PA7gdCeKGaQ/MikeKinney_2017S.mp3", 
                            "id": 1, 
                            "podcast_id": 1, 
                            "published": "2017-10-23T15:13:02", 
                            "title": "A pro wrestler's guide to confidence | Mike Kinney"
                        }
                    ], 
                    "feed_url": "http://feeds.feedburner.com/TEDTalks_audio", 
                    "genres": [
                        {
                            "id": 1, 
                            "itunes_id": 1304, 
                            "name": "Education"
                        }, 

                    ], 
                    "id": 1, 
                    "image_url": "http://is4.mzstatic.com/image/thumb/Music128/v4/d5/c6/50/d5c65035-505e-b006-48e5-be3f0f8f19f8/source/600x600bb.jpg", 
                    "itunes_id": 160904630, 
                    "podcast_genre": [
                         {
                            "id": 1, 
                            "itunes_id": 1304, 
                            "name": "Education"
                        }, 
                    ], 
                    "provider": {
                        "id": 1, 
                        "itunes_id": null, 
                        "name": "TED"
                    }, 
                "provider_id": 1, 
                "title": "TED Talks Daily"
        }

## Episode Collection [/api/episode]
### List all Episodes [GET /api/episode/]

+ Response 200 (application/json)

        {
  "num_results": 1, 
  "objects": [
    {
      "description": "", 
      "file_url": "http://feedproxy.google.com/~r/TEDTalks_audio/~5/PA7gdCeKGaQ/MikeKinney_2017S.mp3", 
      "id": 1, 
      "podcast": {
        "description": "", 
        "feed_url": "http://feeds.feedburner.com/TEDTalks_audio", 
        "id": 1, 
        "image_url": "http://is4.mzstatic.com/image/thumb/Music128/v4/d5/c6/50/d5c65035-505e-b006-48e5-be3f0f8f19f8/source/600x600bb.jpg", 
        "itunes_id": 160904630, 
        "provider_id": 1, 
        "title": "TED Talks Daily"
      }, 
      "podcast_id": 1, 
      "published": "2017-10-23T15:13:02", 
      "title": "A pro wrestler's guide to confidence | Mike Kinney"
    },
    ],
     "page": 1, 
      "total_pages": 1
    }
        
### Get Episode [GET /api/episode/{ID}]
+ Response 200 (application/json)

{
      "description": "", 
      "file_url": "http://feedproxy.google.com/~r/TEDTalks_audio/~5/PA7gdCeKGaQ/MikeKinney_2017S.mp3", 
      "id": 1, 
      "podcast": {
        "description": "", 
        "feed_url": "http://feeds.feedburner.com/TEDTalks_audio", 
        "id": 1, 
        "image_url": "http://is4.mzstatic.com/image/thumb/Music128/v4/d5/c6/50/d5c65035-505e-b006-48e5-be3f0f8f19f8/source/600x600bb.jpg", 
        "itunes_id": 160904630, 
        "provider_id": 1, 
        "title": "TED Talks Daily"
      }, 
      "podcast_id": 1, 
      "published": "2017-10-23T15:13:02", 
      "title": "A pro wrestler's guide to confidence | Mike Kinney"
    }

## Genre Collection [/api/genre]        
### List all Genres [GET /api/genre]

+ Response 200 (application/json)


  "num_results": 1, 
  "objects": [
    {
      "id": 1, 
      "itunes_id": 1304, 
      "name": "Education", 
      "podcast_genre": [
        {
          "description": "", 
          "feed_url": "http://feeds.feedburner.com/TEDTalks_audio", 
          "id": 1, 
          "image_url": "http://is4.mzstatic.com/image/thumb/Music128/v4/d5/c6/50/d5c65035-505e-b006-48e5-be3f0f8f19f8/source/600x600bb.jpg", 
          "itunes_id": 160904630, 
          "provider_id": 1, 
          "title": "TED Talks Daily"
        }
      ], 
      "podcasts": [
        {
          "description": "", 
          "feed_url": "http://theartofcharmpodcast.theartofcharm.libsynpro.com/rss", 
          "id": 88, 
          "image_url": "http://is3.mzstatic.com/image/thumb/Music91/v4/d2/16/cf/d216cf64-f475-fb13-3ec3-b854a0ad18d6/source/600x600bb.jpg", 
          "itunes_id": 212382281, 
          "provider_id": 67, 
          "title": "The Art of Charm | Social Science | Cognitive Psychology | Confidence | Relationship Advice | Behavioral Economics | Productivi"
        }
      ]
    },
    ],
    "page": 1, 
     "total_pages": 1
    }
        

### Get Genre [GET /api/genre/{ID}]
+ Response 200 (application/json)

{
      "id": 1, 
      "itunes_id": 1304, 
      "name": "Education", 
      "podcast_genre": [
        {
          "description": "", 
          "feed_url": "http://feeds.feedburner.com/TEDTalks_audio", 
          "id": 1, 
          "image_url": "http://is4.mzstatic.com/image/thumb/Music128/v4/d5/c6/50/d5c65035-505e-b006-48e5-be3f0f8f19f8/source/600x600bb.jpg", 
          "itunes_id": 160904630, 
          "provider_id": 1, 
          "title": "TED Talks Daily"
        }
      ], 
      "podcasts": [
        {
          "description": "", 
          "feed_url": "http://theartofcharmpodcast.theartofcharm.libsynpro.com/rss", 
          "id": 88, 
          "image_url": "http://is3.mzstatic.com/image/thumb/Music91/v4/d2/16/cf/d216cf64-f475-fb13-3ec3-b854a0ad18d6/source/600x600bb.jpg", 
          "itunes_id": 212382281, 
          "provider_id": 67, 
          "title": "The Art of Charm | Social Science | Cognitive Psychology | Confidence | Relationship Advice | Behavioral Economics | Productivi"
        }
      ]
    }


## Provider Collection [/api/provider]        
### List all Providers [GET /api/provider]

+ Response 200 (application/json)

{
  "num_results": 70, 
  "objects": [
    {
      "id": 1, 
      "itunes_id": null, 
      "name": "TED", 
      "podcasts": [
        {
          "description": "", 
          "feed_url": "http://feeds.feedburner.com/TEDTalks_audio", 
          "id": 1, 
          "image_url": "http://is4.mzstatic.com/image/thumb/Music128/v4/d5/c6/50/d5c65035-505e-b006-48e5-be3f0f8f19f8/source/600x600bb.jpg", 
          "itunes_id": 160904630, 
          "provider_id": 1, 
          "title": "TED Talks Daily"
        }, 
        {
          "description": "", 
          "feed_url": "http://feeds.feedburner.com/SincerelyX", 
          "id": 72, 
          "image_url": "http://is1.mzstatic.com/image/thumb/Music118/v4/18/c4/2f/18c42ff3-abd2-9755-c955-9239fd1e5393/source/600x600bb.jpg", 
          "itunes_id": 1238801741, 
          "provider_id": 1, 
          "title": "Sincerely, X"
        }
      ]
    },
    ],
    "page": 1, 
    "total_pages": 1
}
    
        
### Get Provider [GET /api/provider/{ID}]

+ Response 200 (application/json)

 {
      "id": 1, 
      "itunes_id": null, 
      "name": "TED", 
      "podcasts": [
        {
          "description": "", 
          "feed_url": "http://feeds.feedburner.com/TEDTalks_audio", 
          "id": 1, 
          "image_url": "http://is4.mzstatic.com/image/thumb/Music128/v4/d5/c6/50/d5c65035-505e-b006-48e5-be3f0f8f19f8/source/600x600bb.jpg", 
          "itunes_id": 160904630, 
          "provider_id": 1, 
          "title": "TED Talks Daily"
        }, 
        {
          "description": "", 
          "feed_url": "http://feeds.feedburner.com/SincerelyX", 
          "id": 72, 
          "image_url": "http://is1.mzstatic.com/image/thumb/Music118/v4/18/c4/2f/18c42ff3-abd2-9755-c955-9239fd1e5393/source/600x600bb.jpg", 
          "itunes_id": 1238801741, 
          "provider_id": 1, 
          "title": "Sincerely, X"
        }
      ]
    }