"""empty message

Revision ID: 9e0866ad39f7
Revises: 8a77e8bd0504
Create Date: 2017-10-23 16:03:48.911169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0866ad39f7'
down_revision = '8a77e8bd0504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'podcast_id')
    )
    op.drop_table('genres')
    op.add_column('episode', sa.Column('description', sa.String(), nullable=True))
    op.add_column('episode', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('episode', sa.Column('published', sa.DateTime(), nullable=True))
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('episode_image_url_key', 'episode', type_='unique')
    op.drop_constraint('episode_title_key', 'episode', type_='unique')
    op.drop_column('episode', 'image_url')
    op.add_column('genre', sa.Column('itunes_id', sa.Integer(), nullable=True))
    op.add_column('podcast', sa.Column('itunes_id', sa.Integer(), nullable=True))
    op.alter_column('podcast', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('podcast', 'feed_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('podcast', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('podcast', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('podcast', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('podcast_description_key', 'podcast', type_='unique')
    op.drop_constraint('podcast_feed_url_key', 'podcast', type_='unique')
    op.drop_constraint('podcast_image_url_key', 'podcast', type_='unique')
    op.drop_constraint('podcast_title_key', 'podcast', type_='unique')
    op.add_column('provider', sa.Column('itunes_id', sa.Integer(), nullable=True))
    op.alter_column('provider', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('provider_name_key', 'provider', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('provider_name_key', 'provider', ['name'])
    op.alter_column('provider', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('provider', 'itunes_id')
    op.create_unique_constraint('podcast_title_key', 'podcast', ['title'])
    op.create_unique_constraint('podcast_image_url_key', 'podcast', ['image_url'])
    op.create_unique_constraint('podcast_feed_url_key', 'podcast', ['feed_url'])
    op.create_unique_constraint('podcast_description_key', 'podcast', ['description'])
    op.alter_column('podcast', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('podcast', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('podcast', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('podcast', 'feed_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('podcast', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('podcast', 'itunes_id')
    op.drop_column('genre', 'itunes_id')
    op.add_column('episode', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('episode_title_key', 'episode', ['title'])
    op.create_unique_constraint('episode_image_url_key', 'episode', ['image_url'])
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('episode', 'published')
    op.drop_column('episode', 'file_url')
    op.drop_column('episode', 'description')
    op.create_table('genres',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('podcast_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='genres_genre_id_fkey'),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], name='genres_podcast_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'podcast_id', name='genres_pkey')
    )
    op.drop_table('podcast_genre')
    # ### end Alembic commands ###
